# Generated by Django 2.0.7 on 2018-10-04 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('bolsa', '0006_auto_20180404_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_on', models.DateField(verbose_name='período dapesquisa')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='solicitado em')),
                ('person', models.ManyToManyField(blank=True, related_name='Pessoa', to='person.Person')),
            ],
            options={
                'verbose_name': 'Pesquisa',
                'verbose_name_plural': 'Pesquisas',
                'ordering': ('-participation_on',),
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=200, verbose_name='Pergunta')),
                ('level', models.CharField(choices=[('0', 'Indefinido'), ('1', 'Dependencia'), ('2', 'Confianca'), ('3', 'Comprometimento'), ('4', 'Preditiva'), ('5', 'Comprometimento')], default='0', max_length=15, verbose_name='Nível')),
            ],
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='question',
            field=models.ManyToManyField(blank=True, related_name='Pergunta', to='bolsa.Questions'),
        ),
    ]
