# Generated by Django 2.0.7 on 2018-10-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0007_auto_20181004_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='person',
            field=models.ManyToManyField(related_name='Pessoa', to='person.Person'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='question',
            field=models.ManyToManyField(related_name='Pergunta', to='bolsa.Questions'),
        ),
    ]
