# Generated by Django 2.0.7 on 2018-10-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0008_auto_20181004_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='questions',
            new_name='question',
        ),
    ]
