# Generated by Django 2.0.7 on 2018-10-04 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('bolsa', '0009_auto_20181004_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesquisa',
            name='person',
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Pessoa', to='person.Person'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pesquisa',
            name='question',
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Pergunta', to='bolsa.Questions'),
            preserve_default=False,
        ),
    ]
