# Generated by Django 2.0.7 on 2018-10-04 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0011_pesquisa_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='participation_on',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='período dapesquisa'),
        ),
    ]
