# Generated by Django 2.0.7 on 2018-10-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0012_auto_20181004_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planodecontas',
            options={'ordering': ('classification',), 'verbose_name': 'Plano de contas', 'verbose_name_plural': 'Planos de conta'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ('-level',), 'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='search_key',
            field=models.CharField(db_index=True, default='bolsa.Pesquisa.question', max_length=50, verbose_name='Chave da pesquisa'),
        ),
    ]
