# Generated by Django 2.0.7 on 2018-10-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0013_auto_20181004_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='search_key',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Chave da pesquisa'),
        ),
    ]
