# Generated by Django 2.0.7 on 2018-10-04 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0014_auto_20181004_2044'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pesquisa',
            unique_together={('search_key', 'question')},
        ),
    ]
