# Generated by Django 2.0.7 on 2018-10-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0015_auto_20181004_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='search_key',
            field=models.CharField(max_length=10, verbose_name='Chave da pesquisa'),
        ),
    ]
