# Generated by Django 2.0.7 on 2018-10-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0016_auto_20181010_1002'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pesquisa',
            unique_together={('search_key', 'question', 'question')},
        ),
    ]
