# Generated by Django 2.0.7 on 2018-10-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('bolsa', '0018_auto_20181010_1100'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pesquisa',
            unique_together={('search_key', 'person', 'question', 'response')},
        ),
    ]
