# Generated by Django 2.0.7 on 2019-05-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0022_auto_20181011_0947'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pesquisa',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pesquisa',
            name='person',
        ),
        migrations.RemoveField(
            model_name='pesquisa',
            name='question',
        ),
        migrations.DeleteModel(
            name='Pesquisa',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
