# Generated by Django 2.0.7 on 2019-05-12 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20190511_1116'),
        ('bolsa', '0023_auto_20190511_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_key', models.CharField(max_length=200, verbose_name='Chave da pesquisa')),
                ('response', models.CharField(choices=[('V', 'Verdadeiro'), ('F', 'Falso'), ('I', 'Indefinido')], default='I', max_length=1, verbose_name='Resposta')),
                ('participation_on', models.DateField(verbose_name='período dapesquisa')),
                ('created_on', models.DateTimeField(verbose_name='solicitado em')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pessoa', to='person.Person')),
            ],
            options={
                'verbose_name': 'Pesquisa',
                'verbose_name_plural': 'Pesquisas',
                'ordering': ('-participation_on',),
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Pergunta')),
                ('level', models.CharField(choices=[('0', 'Indefinido'), ('1', 'Dependencia'), ('2', 'Confianca'), ('3', 'Comprometimento'), ('4', 'Preditiva'), ('5', 'Comprometimento')], default='0', max_length=15, verbose_name='Nível')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ('-level',),
            },
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pergunta', to='bolsa.Questions'),
        ),
        migrations.AlterUniqueTogether(
            name='pesquisa',
            unique_together={('search_key', 'person', 'question')},
        ),
    ]
