# Generated by Django 2.0.7 on 2019-05-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0024_auto_20190512_1022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pesquisa',
            unique_together=set(),
        ),
    ]
