# Generated by Django 2.0.7 on 2018-07-31 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_kind', models.CharField(choices=[('in', 'Cliente Pagou'), ('out', 'Cliente Recebeu'), ('eaj', 'Ajuste pagamento do Cliente'), ('saj', 'Ajuste recebimento do Cliente')], max_length=4, verbose_name='Tipo Movimento')),
                ('value_moved', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Movimento')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('date_return', models.DateField(verbose_name='Dt. Retorno..')),
            ],
            options={
                'verbose_name': 'Movimento',
                'verbose_name_plural': 'Movimentos',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo')),
                ('public_place', models.CharField(max_length=150, verbose_name='Logradouro')),
                ('number', models.CharField(max_length=150, verbose_name='Número')),
                ('city', models.CharField(max_length=150, verbose_name='Cidade')),
                ('state', models.CharField(max_length=150, verbose_name='Estado')),
                ('zipcode', models.CharField(max_length=10, verbose_name='Cep')),
                ('neighborhood', models.CharField(max_length=50, verbose_name='Bairro')),
                ('date_of_turn', models.DateField(verbose_name='Dt. Giro.')),
                ('date_return', models.DateField(blank=True, null=True, verbose_name='Dt. Retorno.')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.AddField(
            model_name='movimento',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_item', to='person.Person'),
        ),
    ]
