# Generated by Django 2.0.7 on 2018-07-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimento',
            name='date_of_turn_m',
        ),
        migrations.AddField(
            model_name='movimento',
            name='date_return',
            field=models.DateField(default='2018-05-01', verbose_name='Dt. Giro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='date_return',
            field=models.DateField(default='2018-05-01', verbose_name='Dt. Retorno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_turn_p',
            field=models.DateField(verbose_name='Dt. Giro'),
        ),
    ]
