# Generated by Django 2.0.7 on 2018-07-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_return',
            field=models.DateField(auto_now=True, verbose_name='Dt. Retorno'),
        ),
    ]
