# Generated by Django 2.0.7 on 2019-04-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='created',
            field=models.DateField(verbose_name='created'),
        ),
    ]
