# Generated by Django 2.0.7 on 2018-07-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='purchase_limit',
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(default='Brasil', editable=False, max_length=150, verbose_name='País'),
        ),
    ]
