# Generated by Django 2.0.7 on 2019-05-03 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20190426_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimento',
            options={'ordering': ('person',), 'verbose_name': 'Movimento', 'verbose_name_plural': 'Movimentos'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('name',), 'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
    ]
