# Generated by Django 2.0.7 on 2018-07-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20180730_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_return',
            field=models.DateField(verbose_name='Dt. Retorno'),
        ),
    ]
