# Generated by Django 2.0.7 on 2018-07-16 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_remove_person_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_kind', models.CharField(choices=[('in', 'Cliente Pagou'), ('out', 'Cliente Recebeu'), ('eaj', 'Ajuste pagamento do Cliente'), ('saj', 'Ajuste recebimento do Cliente')], max_length=4, verbose_name='Tipo Movimento')),
                ('value_moved', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Movimento')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name': 'Movimento',
                'verbose_name_plural': 'Movimentos',
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AddField(
            model_name='person',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Saldo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimento',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_item', to='person.Person'),
        ),
    ]
