# Generated by Django 2.0.7 on 2018-07-30 23:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20180730_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='date_return',
            field=models.DateField(default=datetime.datetime(2018, 7, 30, 23, 44, 9, 39705, tzinfo=utc), verbose_name='Dt. Retorno'),
        ),
    ]
