# Generated by Django 2.0.7 on 2019-05-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20190503_0215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimento',
            options={'verbose_name': 'Movimento', 'verbose_name_plural': 'Movimentos'},
        ),
    ]
