# Generated by Django 2.0.7 on 2018-07-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20180730_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='date_return',
            field=models.DateField(blank=True, null=True, verbose_name='Dt. Retorno'),
        ),
    ]
