# Generated by Django 2.0.7 on 2019-05-09 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0004_auto_20190504_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Usuário', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
