# Generated by Django 2.0.7 on 2018-07-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20180730_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='date_return',
            field=models.DateField(verbose_name='Dt. Retorno..'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_turn',
            field=models.DateField(verbose_name='Dt. Giro.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_return',
            field=models.DateField(blank=True, null=True, verbose_name='Dt. Retorno.'),
        ),
    ]
